<link rel="stylesheet" href="{{asset('dist_front/css/bootstrap.min.css')}}">
<link rel="stylesheet" href="{{asset('dist_front/css/jquery-ui.css')}}">
<link rel="stylesheet" href="{{asset('dist_front/css/animate.min.css')}}">
<link rel="stylesheet" href="{{asset('dist_front/css/magnific-popup.css')}}">
<link rel="stylesheet" href="{{asset('dist_front/css/owl.carousel.min.css')}}">
<link rel="stylesheet" href="{{asset('dist_front/css/select2.min.css')}}">
<link rel="stylesheet" href="{{asset('dist_front/css/select2-bootstrap.min.css')}}">
<link rel="stylesheet" href="{{asset('dist_front/css/sweetalert2.min.css')}}">
<link rel="stylesheet" href="{{asset('dist_front/css/spacing.css')}}">
<link rel="stylesheet" href="{{asset('dist_front/css/font_awesome_5_free.min.css')}}">
<link rel="stylesheet" href="{{asset('dist_front/css/style.css')}}">